# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: https://kommu.ai
title: Kommu
email: support@kommu.com
author: Kommu Admin
description: "KommuAssist: Combining AI and IoT for a Level 2 Autonomous Driving Solution"
#  You can edit this line in _config.yml. It will appear in your document 
#  head meta (for Google search results) and in your feed.xml site 
#  description.
copyright: 'Copyright &copy; 2022 Kommu. All Rights Reserved.'

collections:
  products:
    output: true

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram.com/kommuai
  - title: github
    url: https://github.com/kommu/bukapilot
  - title: facebook
    url: https://instagram.com/kommuai

